use serde_json::json;
use std::path::PathBuf;

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct DoctorReport {
    pub(crate) status: &'static str,
    pub(crate) storage: &'static str,
    pub(crate) actions: usize,
    pub(crate) planner: &'static str,
    pub(crate) workflow_dry_run: &'static str,
    pub(crate) index_components: usize,
    pub(crate) index_relations: usize,
    pub(crate) plugins: usize,
    pub(crate) audit_events: usize,
    pub(crate) quality: &'static str,
    pub(crate) quality_ci: &'static str,
    pub(crate) dylint_lint: &'static str,
    pub(crate) quality_tools: Vec<&'static str>,
    pub(crate) source_file_limit: usize,
    pub(crate) config_file_limit: usize,
    pub(crate) config_files: usize,
    pub(crate) max_config_file: PathBuf,
    pub(crate) max_config_lines: usize,
    pub(crate) source_files: usize,
    pub(crate) max_source_file: PathBuf,
    pub(crate) max_source_lines: usize,
    pub(crate) workspace_crates: usize,
    pub(crate) launcher: &'static str,
    pub(crate) studio: &'static str,
    pub(crate) ui_docs: &'static str,
    pub(crate) ui_docs_count: usize,
    pub(crate) launcher_ui_gates: Vec<&'static str>,
    pub(crate) studio_ui_gates: Vec<&'static str>,
    pub(crate) manual_desktop_acceptance: &'static str,
    pub(crate) background_ui_acceptance: &'static str,
    pub(crate) desktop_automation_default: &'static str,
    pub(crate) ui_completion: &'static str,
    pub(crate) completion_audit: &'static str,
    pub(crate) completion_matrix: &'static str,
    pub(crate) completion_areas: Vec<&'static str>,
    pub(crate) completion_manual_blockers: Vec<&'static str>,
    pub(crate) completion_evidence_rules: Vec<&'static str>,
    pub(crate) final_completion: &'static str,
    pub(crate) release_plan: &'static str,
    pub(crate) install_plan: &'static str,
    pub(crate) config_path: PathBuf,
}

impl DoctorReport {
    pub(crate) fn text(&self) -> String {
        format!(
            "doctor {status}\nstorage={storage}\nactions={actions}\nplanner={planner}\nworkflow_dry_run={workflow_dry_run}\nindex_components={index_components}\nindex_relations={index_relations}\nplugins={plugins}\naudit_events={audit_events}\nquality={quality}\nquality_ci={quality_ci}\ndylint_lint={dylint_lint}\nquality_tools={quality_tools}\nsource_file_limit={source_file_limit}\nconfig_file_limit={config_file_limit}\nsource_files={source_files}\nmax_source_file={max_source_file}:{max_source_lines}\nconfig_files={config_files}\nmax_config_file={max_config_file}:{max_config_lines}\nworkspace_crates={workspace_crates}\nlauncher={launcher}\nstudio={studio}\nui_docs={ui_docs}\nui_docs_count={ui_docs_count}\nlauncher_ui_gates={launcher_ui_gates}\nstudio_ui_gates={studio_ui_gates}\nmanual_desktop_acceptance={manual_desktop_acceptance}\nbackground_ui_acceptance={background_ui_acceptance}\ndesktop_automation_default={desktop_automation_default}\nui_completion={ui_completion}\ncompletion_audit={completion_audit}\ncompletion_matrix={completion_matrix}\ncompletion_areas={completion_areas}\ncompletion_manual_blockers={completion_manual_blockers}\ncompletion_evidence_rules={completion_evidence_rules}\nfinal_completion={final_completion}\nrelease_plan={release_plan}\ninstall_plan={install_plan}\nconfig_path={config_path}",
            status = self.status,
            storage = self.storage,
            actions = self.actions,
            planner = self.planner,
            workflow_dry_run = self.workflow_dry_run,
            index_components = self.index_components,
            index_relations = self.index_relations,
            plugins = self.plugins,
            audit_events = self.audit_events,
            quality = self.quality,
            quality_ci = self.quality_ci,
            dylint_lint = self.dylint_lint,
            quality_tools = self.quality_tools.join(","),
            source_file_limit = self.source_file_limit,
            config_file_limit = self.config_file_limit,
            source_files = self.source_files,
            max_source_file = self.max_source_file.display(),
            max_source_lines = self.max_source_lines,
            config_files = self.config_files,
            max_config_file = self.max_config_file.display(),
            max_config_lines = self.max_config_lines,
            workspace_crates = self.workspace_crates,
            launcher = self.launcher,
            studio = self.studio,
            ui_docs = self.ui_docs,
            ui_docs_count = self.ui_docs_count,
            launcher_ui_gates = self.launcher_ui_gates.join(","),
            studio_ui_gates = self.studio_ui_gates.join(","),
            manual_desktop_acceptance = self.manual_desktop_acceptance,
            background_ui_acceptance = self.background_ui_acceptance,
            desktop_automation_default = self.desktop_automation_default,
            ui_completion = self.ui_completion,
            completion_audit = self.completion_audit,
            completion_matrix = self.completion_matrix,
            completion_areas = self.completion_areas.join(","),
            completion_manual_blockers = self.completion_manual_blockers.join("|"),
            completion_evidence_rules = self.completion_evidence_rules.join("|"),
            final_completion = self.final_completion,
            release_plan = self.release_plan,
            install_plan = self.install_plan,
            config_path = self.config_path.display(),
        )
    }

    pub(crate) fn json(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&json!({
            "status": self.status,
            "storage": self.storage,
            "actions": self.actions,
            "planner": self.planner,
            "workflow_dry_run": self.workflow_dry_run,
            "index_components": self.index_components,
            "index_relations": self.index_relations,
            "plugins": self.plugins,
            "audit_events": self.audit_events,
            "quality": self.quality,
            "quality_ci": self.quality_ci,
            "dylint_lint": self.dylint_lint,
            "quality_tools": self.quality_tools,
            "source_file_limit": self.source_file_limit,
            "config_file_limit": self.config_file_limit,
            "config_files": self.config_files,
            "max_config_file": self.max_config_file,
            "max_config_lines": self.max_config_lines,
            "source_files": self.source_files,
            "max_source_file": self.max_source_file,
            "max_source_lines": self.max_source_lines,
            "workspace_crates": self.workspace_crates,
            "launcher": self.launcher,
            "studio": self.studio,
            "ui_docs": self.ui_docs,
            "ui_docs_count": self.ui_docs_count,
            "launcher_ui_gates": self.launcher_ui_gates,
            "studio_ui_gates": self.studio_ui_gates,
            "manual_desktop_acceptance": self.manual_desktop_acceptance,
            "background_ui_acceptance": self.background_ui_acceptance,
            "desktop_automation_default": self.desktop_automation_default,
            "ui_completion": self.ui_completion,
            "completion_audit": self.completion_audit,
            "completion_matrix": self.completion_matrix,
            "completion_areas": self.completion_areas,
            "completion_manual_blockers": self.completion_manual_blockers,
            "completion_evidence_rules": self.completion_evidence_rules,
            "final_completion": self.final_completion,
            "release_plan": self.release_plan,
            "install_plan": self.install_plan,
            "config_path": self.config_path,
        }))
    }
}
